### ISSUE TITLE
Warnings are bright yellow on white text = unreadable

### ISSUE THREAD

**Issue by 0xmdl** [huacnlee/zed-theme-macos-classic#1]
Thank you for creating this theme!

With some quick testing, the theme seems to be broken around warnings as per the screenshot below. Broken for both "Dark" and "Dark2". Looks fine on "Light".

Glancing at the json file, I couldn't locate the value for this warning.

<img width="722" alt="macos-classic-warning" src="https://github.com/huacnlee/zed-theme-macos-classic/assets/160384291/64e5089f-327c-4951-b3e1-08b0ee33c111">

**Comment by huacnlee** [comment]
<img width="1162" alt="image" src="https://github.com/huacnlee/zed-theme-macos-classic/assets/5518/9c8b3160-0b65-41f1-b3e2-9c6e778b9b65">
<img width="1162" alt="image" src="https://github.com/huacnlee/zed-theme-macos-classic/assets/5518/b8d2957d-c353-49db-b9e1-255a1f3fea88">
<img width="1162" alt="image" src="https://github.com/huacnlee/zed-theme-macos-classic/assets/5518/7afb2770-a3b2-49bc-b49f-7dd8618e95d9">

New style, wait update extension.

**Comment by 0xmdl** [comment]
Thanks! Looks better now.
