### ISSUE TITLE
Terminal "note" colour is incorrect

### ISSUE THREAD

**Issue by 0xmdl** [huacnlee/zed-theme-macos-classic#2]
A bit more testing reveals some issues with terminal colours. This affects the three variations of the theme. Light, Dark, and Dark2. On Light, the "note" text colour is pure white, and for Dark and Dark2 is pure black.

<img width="867" alt="Screenshot 2024-02-19 at 3 34 32 am" src="https://github.com/huacnlee/zed-theme-macos-classic/assets/160384291/e3f7e3d8-cd0c-47d6-bb72-d5042e42b6c7">

<img width="867" alt="Screenshot 2024-02-19 at 3 35 22 am" src="https://github.com/huacnlee/zed-theme-macos-classic/assets/160384291/6c1bc8a9-bf2d-43bf-b5bd-affb317d5165">

<img width="532" alt="Screenshot 2024-02-19 at 3 35 04 am" src="https://github.com/huacnlee/zed-theme-macos-classic/assets/160384291/eb8298bd-9b10-4e3f-beaf-be82abf778c1">

**Comment by 0xmdl** [comment]
@huacnlee thanks once again for the quick fix!
On a side note, this issue seems to be consistent with all the default themes that come with Zed, or is it just me?

**Comment by huacnlee** [comment]
It's because I was not done with all color variables.
