### ISSUE TITLE
Scroll bar thumb should better be transparent.

### ISSUE THREAD

**Issue by Congyuwang** [huacnlee/zed-theme-macos-classic#4]
https://github.com/huacnlee/zed-theme-macos-classic/assets/52687642/12367a21-5436-447b-acf0-26e1ff79e9bc

The scroll bar thumb covers the highlights of the scroll bar.

I think maybe it is better to give `scrollbar_thumb.background` and `scrollbar.thumb.border ` an alpha value, such as:

https://github.com/catppuccin/zed/blob/066afb8ba5eeb867106080e8ca28c5431ffde3a8/themes/catppuccin.json#L51-L55

```json
        "scrollbar_thumb.background": "#acb0be80",
        "scrollbar.thumb.hover_background": "#9ca0b0",
        "scrollbar.thumb.border": "#acb0be80",
        "scrollbar.track.background": "#eff1f5",
        "scrollbar.track.border": "#4c4f6912",
```

Related: https://github.com/zed-industries/zed/issues/8705

**Comment by huacnlee** [comment]
Fixed
